spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pre_project
    username: root
    password: ken343611@
